import matplotlib.pyplot as plot
import numpy as py
f1=input("enter the frequency 1")
f2=input("enter the requency 2")
fs=input("enter sampling frequency")
t=py.arange(0,100,0.25)
a=py.sin((2*py.pi*f1*t)/fs)
plot.subplot(1,3,1)
plot.plot(t,a)
plot.title("sine wave")
plot.xlabel("---------->time")
plot.ylabel("---------->amplitude")
b=py.cos((2*py.pi*f2*t)/fs)
plot.subplot(1,3,2)
plot.plot(t,b)
plot.title("cos wave")
plot.xlabel("---------->time")
plot.ylabel("---------->amplitude")
plot.show()
