import matplotlib.pyplot as plot
import numpy as py
f=input("enter the frequency")
fs=input("enter sampling frequency")
t=py.arange(0,100,0.25)
a=py.sin((2*py.pi*f*t)/fs)
plot.subplot(1,3,1)
plot.plot(t,a)
plot.title("sine wave")
plot.xlabel("---------->time")
plot.ylabel("---------->amplitude")
b=py.cos((2*py.pi*f*t)/fs)
plot.subplot(1,3,2)
plot.plot(t,b)
plot.title("cos wave")
plot.xlabel("---------->time")
plot.ylabel("---------->amplitude")
c=a+b
plot.subplot(1,3,3)
plot.plot(t,c)
plot.title("addition of sine & cos wave")
plot.xlabel("----------->time")
plot.ylabel("----------->amplitude") 
plot.show()
